### ISSUE TITLE
Please remove the Chinese year in this repository

### ISSUE THREAD

**Issue by maximumpower1** [asgrim/year#12]
The Chinese year in this repository is nonsense. [Even though this repository is nonsense but... ]

I am Chinese and I never heard about 4713 year or anything related to this meaningless number.

* This calendar is based on a [legendary hero](https://en.wikipedia.org/wiki/Yellow_Emperor)'s birthday which was living in 2698–2598 BC.
* The first record of this legendary hero was written in 390-338 BC, which is unreliable.
* **The Chinese society is not using this calendar.**
* There was only one warlord used it and it was deprecated within a year.
* The only article that talking about this calendar on Wikipedia is [this](https://zh.wikipedia.org/wiki/%E9%BB%84%E5%B8%9D%E7%BA%AA%E5%85%83) and it is categorized as an unreferenced article. (And it doesn't even have an English translation.)

**Comment by asgrim** [comment]
Okaay, I think you took this repo a little too seriously :) thanks though!
