### ISSUE TITLE
[feature] Add method that returns range of years

### ISSUE THREAD

**Issue by cerlestes** [asgrim/year#13]
It would be great if we could not only retrieve the current, next and previous years, but also an arbitrary range of years, maybe capped at -100 to +100.

I understand that it's somewhat complex to realise with the current API, but I'm sure a lot of users would profit from this.

`GET /range/-2/+1/` could then return: 

```
[2013, 2014, 2015, 2016]
```

Thanks for providing this useful service though.

**Comment by dann95** [comment]
this project is called Year, not years =/ maybe a project called Years can be created.
