### ISSUE TITLE
2020 is a leap year

### ISSUE THREAD

**Issue by fangyi-zhou** [asgrim/year#34]

**Comment by asgrim** [comment]
Not sure if this has any impact anyway since we don't return that sort of information, unless you are proposing a new endpoint...?

**Comment by fangyi-zhou** [comment]
https://github.com/asgrim/year/blob/master/en/isLeapYear

**Comment by asgrim** [comment]
Oh hey, I totally didn't even realise that existed :sweat_smile: fixed now, thanks!
